Feature/dossier/mc dossier
RyaRom/CreditConveyor pull request #17
Opened 2024-09-12 15:20 UTC by RyaRom

2024-09-12 15:24 UTC, Anon12421 commented on application/src/main/java/com/application/model/dto/LoanApplicationRequestDTO.java
test

2024-09-15 18:02 UTC, MichaelDeyev requested changes

2024-09-15 18:02 UTC, MichaelDeyev commented on deal/.idea/vcs.xml
папку .idea нужно добавить в gitignore

2024-09-15 18:02 UTC, MichaelDeyev commented on deal/src/main/java/com/deal/kafka/EmailProducer.java
> +@AllArgsConstructor
@RequestArgsConstructor более подходит для внедрения зависимостей

2024-09-15 18:02 UTC, MichaelDeyev commented on deal/src/main/java/com/deal/model/mapping/DataMapper.java
>  @Mapper(componentModel = "spring")
На всякий случай предупрежу- в реальной коммерческой разработке практически никогда не используется mapstruct. С ним может быть больше проблем, чем пользы, особенно со сложными сущностями.
Сейчас оставь, но на будущее имей ввиду

2024-09-15 18:02 UTC, MichaelDeyev commented on deal/src/main/java/com/deal/service/ApplicationService.java
> +@Transactional
избегай @Transactional на классе. Лучше на каждый метод, который сохраняет сущность в БД повешай эту аннотацию, чем на весь класс сразу

2024-09-15 18:02 UTC, MichaelDeyev commented on deal/src/main/java/com/deal/service/ApplicationService.java
> +        applicationRepo.save(application);
тут и 6 строками выше идут одинаковые действия. Подумаю, можно ли соптимизировать и смержить в 1 сохранение

2024-09-15 18:02 UTC, MichaelDeyev commented on dossier/src/main/java/com/dossier/exception/GlobalExceptionHandler.java
> +                .timestamp(new Date())
Лучше дату не через new Date(), а используя LocalDateTime.now()

2024-09-15 18:02 UTC, MichaelDeyev commented on dossier/src/main/java/com/dossier/model/dto/CreditDTO.java
> +public class CreditDTO {
А сваггер работает с java records? Если да, то лучше на record поменяй

2024-09-27 11:48 UTC, MichaelDeyev approved these changes

2024-09-27 11:48 UTC, MichaelDeyev commented on gateway/mvnw
> +#!/bin/sh
лучше этот файл в гитигнор добавить

2024-09-27 11:48 UTC, MichaelDeyev commented on gateway/mvnw.cmd
> +<# : batch portion
лучше этот файл в гитигнор добавить

2024-09-27 17:35 UTC, merged